kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-react-stack-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-react-stack-pod
  template:
    metadata:
      labels:
        app: go-react-stack-pod
    spec:
      containers:
      - name: go-react-stack-pod
        image: hetelek/go-react-stack:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "50Mi"
            cpu: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: go-react-stack-service
spec:
  selector:
    app: go-react-stack-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
